export const ADD_EVENT_START = "ADD_EVENT_START";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAILURE = "ADD_EVENT_FAILURE";

export const RECEIVE_EVENTS = "RECEIVE_EVENTS";
export const ADD_USER = "ADD_USER";
export const RECEIVE_USERS = "RECEIVE_USERS";
export const SLICE_EVENTS = "SLICE_EVENTS";

export const DELETE_EVENT = "DELETE_EVENT";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";
